# Generated by Django 4.1.7 on 2023-04-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribe el nombre la pelicula', max_length=64)),
                ('fecha_estreno', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Escribe el descripción la pelicula', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribe el nombre del director', max_length=64)),
                ('apelido', models.CharField(help_text='Escribe el nombre del director', max_length=64)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peliculas', models.ManyToManyField(to='cine.pelicula')),
            ],
        ),
    ]
